### PR TITLE
support loading parsers at runtime

### PR DESCRIPTION
**Pull request by mjyrkl**
only runtime loading with compile time configuration is implemented.
issue #123

### CODE REVIEW

**Comment by hetky** [comment]
shared libraries are built with meson for coverage test

**Comment by hetky** [comment]
rebased

**Comment by hetky** [comment]
rebased

**Comment by Wilfred** [comment]
Thanks for the PR! I agree this is a useful feature, but I can't merge it as-is:

(1) If it's using the system tree-sitter library, it needs to use the corresponding `highlights.scm` file. tree-sitter requires the names in the highlights library to match the parse tree.

(2) I don't understand why you've added meson. Is it necessary? Could it just use a Makefile instead?

(3) Could you add a test? I'd like to see the unit tests pass in this mode, or ideally `compare_all.sh`.

(4) Does `--list-languages` still work in this case? What happens if a user has `libtree-sitter-python` but not `libtree-sitter-ruby` installed?

(5) How do I add new languages in this model?

**Review by Wilfred — CHANGES_REQUESTED** [review]
See comment above.

**Comment by hetky** [comment]
(2) Replaced meson with cmake
(3) CI now runs unit tests and regression test for both static and dynamic linking
(4) `--list-languages` prints all supported languages but doesn't check if library is installed.
If user has libtree-sitter-python but not libtree-sitter-ruby installed:
```
# difft old.py new.py
--- normal output

# difft old.py new.rb
--- panic

# difft new.rb new.rb
--- panic

# difft --list-languages
--- normal output
```
(5) Cmake searches `parser.c,scanner.{c}c` in `tree-sitter-$lang-src` directories with hard coded handler for ocaml and typescript.

(5.1) If new language uses same naming scheme it will  be compiled automatically otherwise CI will probably fail. Special treatment is needed for some libraries (ocaml and typescript).

(5.2) Information about new language must be added in `dynlibs.rs` in `ts_function_name`, `ts_library_name` and `functions` mod.
In fact we can get name of function and library with `"tree-sitter-lang".replace("-","_)` and `format!("lib{tree-sitter-lang}")` if it's preferred.

**Comment by Wilfred** [comment]
Thanks for following up! :)

Could we avoid panicking if a user tries to diff a file and the parser is absent? It's really frustrating to doing `git log` and difftastic crashes, as it stops showing commits beyond that point.

**Pull request closed without merging**
