### PR TITLE
Add Objective-C support

### PR DESCRIPTION
**Pull request by pilotmoon**
If merged, this pull request will add support for diffing Objective-C files to difftastic.

It uses @jiyee's ObjC tree-sitter: https://github.com/jiyee/tree-sitter-objc (MIT License)

I have prepared the pull request according to the instructions at https://difftastic.wilfred.me.uk/adding_a_parser.html

Testing: I have performed basic tests by diffing my own ObjC codebases, and the output is as expected.

Two regression test files are included, one `.m` file and one ObjC `.h` file.

## Note on `.h` files

Objective-C uses a `.h` suffix for header files, the same as C and C++. Since `.h` is allocated to C++ in difftastic, I have added a custom function `looks_like_objc()` in `guess_languages.rs` that uses a simple heuristic to distinguish an Objective-C header from a C/C++ one.

## Screenshot

CleanShot 2023-12-06 at 12 55 32@2x

### CODE REVIEW

**Comment by pilotmoon** [comment]
Additional commit 839ca6d80 adds `number_expression` and `boolean_expression` as atomics:

**Comment by Wilfred** [comment]
Thanks! I see there are several objective-C parsers:

* https://github.com/jiyee/tree-sitter-objc
* https://github.com/amaanq/tree-sitter-objc
* https://github.com/merico-dev/tree-sitter-objc

Which one is best?

**Comment by pilotmoon** [comment]
A good question. I only looked at https://tree-sitter.github.io/tree-sitter/#available-parsers and picked the one that was listed there.

**Comment by pilotmoon** [comment]
What approach would you suggest for performing an evaluation of the relative merits of these parsers? I've done a cursory "github shakedown" of the three and they are all similar in terms of activity, stars, forks etc. There is nothing obvious to favour one based on a superficial examination.

I'm not very familiar with tree-sitter or with the world of parsers, but I am very familair with objc.

I'm not sure how I'd evaluate parsers. My first thought was to incorporate each of the other two into my difft build and try them But then I'm not sure what basis I would evaluate, so I'd want to come up with a test plan of some kind and produce a range of sample output for comparison.

I also asked the computer this and it said:

> To evaluate different Tree-Sitter parser implementations for the same language, you should consider the following criteria:
> 
> 1. **Accuracy**: Evaluate how accurately each parser implementation recognizes various language constructs. This can be done by parsing a diverse set of code samples and checking for parsing errors or incorrect syntax tree structures.
> 
> 2. **Performance**: Measure the parsing speed and memory usage of each implementation. This is important for applications where performance is critical.
> 
> 3. **Robustness**: Test the parser's ability to handle edge cases and syntactically incorrect code. A robust parser should gracefully handle errors and provide useful information about them.
> 
> 4. **Ease of Integration**: Assess how easy it is to integrate the parser into existing systems. Consider factors like language bindings, build system compatibility, and documentation quality.
> 
> 5. **Community Support and Development Activity**: Check the community support for each implementation. A parser with active development and a supportive community is more likely to receive updates and bug fixes.
> 
> 6. **Feature Set**: Compare the features offered by each parser, such as syntax highlighting, code folding, and error recovery capabilities.
> 
> 7. **Customizability**: Determine how easily each parser can be customized or extended to suit specific needs.
> 
> 8. **License and Compatibility**: Ensure that the parser's license is compatible with your project's licensing requirements.
> 
> To conduct this evaluation, you can create a set of test cases that cover a wide range of language features and edge cases. Use these test cases to assess each criterion for each parser implementation. Additionally, consider using existing benchmarks or community feedback as part of your evaluation process.

I feel like of these accuracy is really the only one that might distinguish them as I assume all will be similar in terms of performance and other factors.

This is really just me thinking out loud. I'll just leave these thoughts here for now.

**Comment by pilotmoon** [comment]
As a hack, perhaps I could ask the experts: @jiyee, @amaanq, @merico-dev: which Objective-C parser one should @Wilfred choose for his fantastic structural diff tool?

**Comment by Wilfred** [comment]
Thanks for the PR! I've taken your logic and combined it with the amaanq parser for objective-C :)

I chose this one because Amaan has contributed to a bunch of tree-sitter stuff, and it has the most recent commits.

It does have a small number of parse errors of one of your sample files, but it looks good to me overall. Let me know if you see any issues.

**Comment by pilotmoon** [comment]
Awesome. I checked out and built from master and I too am getting parser errors on the opbjc_module_* files.

Regarding the parser errors on the sample files, is there an easy way I can view the parser error output, to figure out what the errors are? I'd like to understand what's going on.

However, running it against diffs of my actual code bases, it seems to be working OK.

**Comment by Wilfred** [comment]
@pilotmoon you can do `difft --dump-ts your_file.m` and see where the ERROR nodes are. In the case of these test files, it's here:

```
typedef NS_ENUM(NSUInteger, DataOutcome) {
    DataOutcomeContinue,
    DataOutcomeClose,
    DataOutcomeKeepAlive,
};
```

Macros are a hard problem for tree-sitter parsers in general, because they don't have the macro definitions.

**Comment by amaanq** [comment]
Glad to see my parser was incorporated in difftastic! :)

With the macro parsing issue, that's just a problem all C-family languages have and can't really be solved without being context-aware sadly.

**Pull request closed without merging**
