### PR TITLE
don't use softlink for cross platform building

### PR DESCRIPTION
**Pull request by CGQAQ**
FIXED: #426
FIXED: #424
FIXED: #67

### CODE REVIEW

**Comment by CGQAQ** [comment]
image

it should not fail 'cause `vendor/tree-sitter-json/src/parser.c` exists

**Comment by CGQAQ** [comment]
@Wilfred could you please take a look

**Comment by Wilfred** [comment]
If you can get the build to go green, I'd be happy to remove the symlinks. They are currently necessary though. Cargo will refuse to package directories that contain `Cargo.toml` files, so I need a symlink to the `vendor/foo/src` directory to ensure everything goes in the package. It's also important for package size: difftastic is already over the 10MiB default limit for package size, even after my changes.

**Comment by Kreijstal** [comment]
Why not have subpackages?

**Comment by Wilfred** [comment]
They're C libraries, not crates FWIW.

**Pull request closed without merging**
