### PR TITLE
Use successors

### PR DESCRIPTION
**Pull request by Masynchin**
Use successors instead of hand-made loop.

@QuarticCat I have slightly refactored your changes from #393, can you measure speed up/downgrading?

### CODE REVIEW

**Comment by Masynchin** [comment]
@Wilfred it seems that tests doesn't cover `Stack::size`. For example,

~~~diff
pub fn size(&self) -> usize {
-    successors(self.head.as_ref(), |node| node.next.as_ref()).count()
+    successors(self.head.as_ref(), |node| node.next.as_ref()).count() + 100
}
~~~

passes the tests.

**Comment by QuarticCat** [comment]
Actually, this function was only used in a debug output, which should not have an impact on the performance. And it was removed from #395.

**Comment by QuarticCat** [comment]
By the way, I am planning the next big performance improvement PR, in which I completely refactored the stack. https://github.com/QuarticCat/difftastic/blob/new-thoughts/src/diff/graph.rs#L126

**Comment by Masynchin** [comment]
> And it was removed in #395.

Seems that my PR is no longer relatable :(

**Pull request closed without merging**
