### PR TITLE
Add Hare support

### PR DESCRIPTION
**Pull request by esawady**
https://harelang.org

### CODE REVIEW

**Comment by Wilfred** [comment]
This is looking pretty good! Could you fix the compare.expected file? It looks like it's reordered files, but I imagine this has been fixed by #360.

**Review by Wilfred — CHANGES_REQUESTED** [review]
Once compare.expected is sorted, this is good to merge :)

**Comment by esawady** [comment]
That didn't fix it for me (my guess is that the issue might be related to musl?) but I manually undid the reordering in compare.expected. ¯\\\_(ツ)\_/¯

**Comment by Wilfred** [comment]
Weird. I should probably change the script to explicitly sort the file names rather than relying on order of files when globbing.

**Comment by Wilfred** [comment]
Thanks for the PR! :)

**Pull request merged**
