### PR TITLE
add option and help text for --strip-trailing-cr feature

### PR DESCRIPTION
**Pull request by spital**
This is a work in progress, no functionality present at the moment.
What are the thoughts please, is it worth developing ?

image

### CODE REVIEW

**Comment by Wilfred** [comment]
What's the goal here? Are you trying to normalise the output, or change the input to the diffing logic?

**Comment by spital** [comment]
I should have been more verbose. It is the same as with normal diff. As the name says, it strips the trailing CR in input files. If you have one file created on Windows (CRLF end of lines) and you diff it against one on linux e.g. processed with dos2unix (LF endings), you get that the whole file was changed, which is wrong, files are the same, only line endings are not.

**Comment by Narcha** [comment]
This would be very useful. I use WSL at work, and difftastic is almost useless for diffing files across the WSL boundary because of different line endings. I have to resort to `diff --ignore-space-change` in these cases, but I would much rather use difftastic.

**Comment by Wilfred** [comment]
Done, thanks for the examples! :)

**Comment by Narcha** [comment]
Thank you :heart:

**Pull request closed without merging**
