### PR TITLE
Smali language support

### PR DESCRIPTION
**Pull request by evanrichter**
Following the guide for language support was pretty straight forward, thanks for the great docs!

This adds support for the Smali language, which is the human readable bytecode form of android APKs.

Before:

image

After:

image

### CODE REVIEW

**Comment by amaanq** [comment]
Wow, it's cool to see people actually using the smali parser :grin:!

**Comment by evanrichter** [comment]
> Wow, it's cool to see people actually using the smali parser :grin:! 

I added support to the Helix editor recently too! It's a wonder how much syntax highlighting helps

**Comment by amaanq** [comment]
Smali is what got me into tree-sitter in the first place - I wanted syntax highlighting for it so bad in Neovim after moving away from vscode when reverse engineering android stuff :sweat_smile:

**Comment by Wilfred** [comment]
Thanks! :)

**Pull request merged**
