### PR TITLE
fix(build): add rerun trigger for git HEAD and commit

### PR DESCRIPTION
**Pull request by eth3lbert**
- fix(build): add rerun trigger for git HEAD and commit

### CODE REVIEW

**Comment by Wilfred** [comment]
This seems correct, but it's going to re-run the whole build script on every commit. That seems like a big disadvantage when there are so many C libraries that are compiled by the build script.

**Comment by eth3lbert** [comment]
Correct me if I'm wrong.
I got following output with `cargo build --timings`
<details>
<summary>Clean build graph</summary>
clean-build
</details>

<details>
<summary>Recompile</summary>
incremental
</details>

So I thought it still benefit from incremental compilation.

**Comment by Wilfred** [comment]
I think your machine has a lot more CPUs than my thinkpad :)

Screenshot from 2023-09-18 08-38-00

You're correct that the other dependencies aren't rebuilt, but the build script time is by far the longest on my machine.

**Comment by Wilfred** [comment]
Based on the additional build time, I'm going to close this. Thanks for taking the time to write the code and measure it :)

**Pull request closed without merging**
